# Generated by Django 5.1.1 on 2024-10-11 14:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.PositiveIntegerField(unique=True)),
                ('company_name', models.CharField(max_length=300)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('weight_constant', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Business.position')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', related_query_name='purchase_order', to='Business.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', related_query_name='purchase_order', to='Business.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[(0, 'CONTADO'), (1, 'CRÉDITO')], default=0, max_length=20)),
                ('time_unit', models.PositiveIntegerField(choices=[(0, 'N/A'), (1, 'Días'), (2, 'Semana'), (3, 'Meses'), (4, 'Años')], default=0)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Business.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(blank=True, editable=False)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caliber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('film_color', models.CharField(max_length=25)),
                ('additive', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('sealing_type', models.PositiveIntegerField(choices=[(0, 'Sin sellado'), (1, 'Lateral'), (2, 'Fondo'), (3, 'Manual'), (4, 'Precorte'), (5, 'En "V"')], default=0)),
                ('flap_type', models.PositiveIntegerField(choices=[(0, 'Sin solapa'), (1, 'Interna'), (2, 'Interna doble'), (3, 'Externa'), (4, 'Volada')], default=0)),
                ('flap_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gussets_type', models.PositiveIntegerField(choices=[(0, 'Sin fuelles'), (1, 'Lateral'), (2, 'Fondo')], default=0)),
                ('first_gusset', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('second_gusset', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tape', models.PositiveIntegerField(choices=[(0, 'Sin cinta'), (1, 'Resellable'), (2, 'De seguridad')], default=0)),
                ('die_cut_type', models.PositiveIntegerField(choices=[(0, 'Sin troquel'), (1, 'Riñon'), (2, 'Camiseta'), (3, 'Perforaciones'), (4, 'Banderin'), (5, 'Cordon'), (6, 'Cubrevestido'), (7, 'Media luna'), (8, 'Selle de refuerzo')], default=0)),
                ('roller_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dynas_treaty_faces', models.PositiveIntegerField(choices=[(0, 'Ninguna'), (1, '1 cara'), (2, '2 caras')], default=0)),
                ('pantones_quantity', models.PositiveBigIntegerField()),
                ('pantones_codes', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('sketch_ult', models.URLField(default='https://res.cloudinary.com/db5lqptwu/image/upload/v1728476524/sketches/hlmgblou2onqaf0efh6b.webp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', related_query_name='reference', to='Business.customer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', related_query_name='reference', to='Business.material')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', related_query_name='reference', to='Business.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='PODetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caliber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('film_color', models.CharField(max_length=25)),
                ('kilograms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.PositiveIntegerField()),
                ('kilogram_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additive', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('sealing_type', models.PositiveIntegerField(choices=[(0, 'Sin sellado'), (1, 'Lateral'), (2, 'Fondo'), (3, 'Manual'), (4, 'Precorte'), (5, 'En "V"')], default=0)),
                ('flap_type', models.PositiveIntegerField(choices=[(0, 'Sin solapa'), (1, 'Interna'), (2, 'Interna doble'), (3, 'Externa'), (4, 'Volada')], default=0)),
                ('flap_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gussets_type', models.PositiveIntegerField(choices=[(0, 'Sin fuelles'), (1, 'Lateral'), (2, 'Fondo')], default=0)),
                ('first_gusset', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('second_gusset', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tape', models.PositiveIntegerField(choices=[(0, 'Sin cinta'), (1, 'Resellable'), (2, 'De seguridad')], default=0)),
                ('die_cut_type', models.PositiveIntegerField(choices=[(0, 'Sin troquel'), (1, 'Riñon'), (2, 'Camiseta'), (3, 'Perforaciones'), (4, 'Banderin'), (5, 'Cordon'), (6, 'Cubrevestido'), (7, 'Media luna'), (8, 'Selle de refuerzo')], default=0)),
                ('roller_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dynas_treaty_faces', models.PositiveIntegerField(choices=[(0, 'Ninguna'), (1, '1 cara'), (2, '2 caras')], default=0)),
                ('pantones_quantity', models.PositiveBigIntegerField()),
                ('pantones_codes', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('production_observations', models.TextField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=150)),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_new_sketch', models.BooleanField(default=False)),
                ('sketch_ult', models.URLField(default='https://res.cloudinary.com/db5lqptwu/image/upload/v1728476524/sketches/hlmgblou2onqaf0efh6b.webp')),
                ('wo_number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', related_query_name='order_detail', to='Business.material')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', related_query_name='order_detail', to='Business.producttype')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', related_query_name='detail', to='Business.purchaseorder')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', related_query_name='order_detail', to='Business.reference')),
            ],
        ),
    ]
