# Generated by Django 5.1.1 on 2024-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='entity',
            field=models.CharField(default='Beiplas', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='iva',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
