# Generated by Django 5.1.1 on 2024-10-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_employee_entity_alter_purchaseorder_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', related_query_name='purchase_order', to='Business.employee'),
            preserve_default=False,
        ),
    ]
