# Generated by Django 5.1.1 on 2024-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_alter_purchaseorder_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='measure_unit',
            field=models.PositiveIntegerField(choices=[(0, 'cm'), (1, 'pulg')], default=0),
        ),
    ]
