# Generated by Django 5.1.1 on 2024-10-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0009_alter_employee_position_alter_payment_purchase_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
