# Generated by Django 5.1.1 on 2024-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_rename_second_name_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='podetail',
            old_name='sketch_ult',
            new_name='sketch_url',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='sketch_ult',
            new_name='sketch_url',
        ),
        migrations.AlterField(
            model_name='employee',
            name='entity',
            field=models.CharField(max_length=200),
        ),
    ]
