# Generated by Django 5.1.1 on 2024-10-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0011_product_rename_sketch_ult_podetail_sketch_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', related_query_name='product', to='Business.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', related_query_name='product', to='Business.producttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
