# Generated by Django 5.1.1 on 2024-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0012_product_material_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference',
            field=models.TextField(blank=True),
        ),
    ]
