# Generated by Django 5.1.1 on 2024-10-29 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0013_alter_reference_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pantones_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
