# Generated by Django 5.1.1 on 2024-10-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0014_alter_reference_pantones_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetail',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PODetailChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_data', models.JSONField()),
                ('changed_fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', related_query_name='change_log', to='Business.podetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
