# Generated by Django 5.1.1 on 2024-10-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0015_podetail_is_updated_podetailchangelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podetail',
            name='observations',
        ),
        migrations.AddField(
            model_name='podetail',
            name='measure_unit',
            field=models.PositiveIntegerField(choices=[(0, 'cm'), (1, 'pulg')], default=0),
        ),
        migrations.AddField(
            model_name='podetail',
            name='reference_internal',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
