# Generated by Django 5.1.1 on 2024-10-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0016_remove_podetail_observations_podetail_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='wo_number',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
    ]
