# Generated by Django 5.1.1 on 2024-11-05 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0019_rename_method_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='additive',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
