# Generated by Django 5.1.1 on 2024-11-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0021_alter_payment_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='has_iva',
            field=models.BooleanField(default=True),
        ),
    ]
