# Generated by Django 5.1.1 on 2024-11-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_purchaseorder_has_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Business.purchaseorder'),
        ),
    ]
