# Generated by Django 5.1.1 on 2024-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0024_rename_is_updated_podetail_was_annulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='was_annulled',
            field=models.BooleanField(default=False),
        ),
    ]
