# Generated by Django 5.1.1 on 2024-11-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0025_purchaseorder_was_annulled'),
    ]

    operations = [
        migrations.CreateModel(
            name='POChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_data', models.JSONField()),
                ('changed_fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', related_query_name='change_log', to='Business.purchaseorder')),
            ],
        ),
    ]
