# Generated by Django 5.1.1 on 2024-10-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.PositiveIntegerField(choices=[(0, 'N/A'), (1, 'Extrusión'), (2, 'Impresión'), (3, 'Sellado'), (4, 'Manualidad')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_material_type', models.PositiveIntegerField(choices=[(0, 'Materia prima'), (1, 'Recuperado'), (2, 'Aditivos'), (3, 'Tintas y pigmentos')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField(choices=[(0, 'N/A'), (1, 'Extrusión'), (2, 'Impresión'), (3, 'Sellado'), (4, 'Manualidad')], default=0)),
                ('total_finished_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_finished_units', models.PositiveIntegerField(default=0)),
                ('total_waste_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('theorical_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Extrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.PositiveIntegerField(choices=[(0, 'Tubular'), (1, 'Semi-tubular'), (2, 'Lamina'), (3, 'Lami-doble')], default=0)),
                ('rolls_quantity', models.PositiveSmallIntegerField()),
                ('caliber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.TextField()),
                ('next', models.PositiveIntegerField(choices=[(0, 'Terminado'), (1, 'Extrusión'), (2, 'Impresión'), (3, 'Sellado'), (4, 'Manualidad')], default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrusions', related_query_name='extrusion', to='Production.machine')),
            ],
        ),
        migrations.CreateModel(
            name='R_RawMaterial_Extrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extrusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', related_query_name='material', to='Production.extrusion')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrusions', related_query_name='extrusion', to='Production.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='TouchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished_units', models.PositiveIntegerField(blank=True, null=True)),
                ('waste_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='touchs', related_query_name='touch', to='Business.employee')),
                ('touch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', related_query_name='detail', to='Production.touch')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_observations', models.TextField(blank=True, null=True)),
                ('surplus_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_weight', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('surplus_weight', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('wo_weight', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Sin iniciar'), (1, 'En extrusión'), (2, 'En impresión'), (3, 'En sellado'), (4, 'En manualidad'), (5, 'En bodega'), (6, 'Terminado')], default=0)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('po_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', related_query_name='work_order_query', to='Business.podetail')),
            ],
        ),
        migrations.AddField(
            model_name='touch',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touch', related_query_name='touch_query', to='Production.workorder'),
        ),
        migrations.CreateModel(
            name='Sealing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hits', models.PositiveIntegerField()),
                ('package_units', models.PositiveIntegerField()),
                ('bundle_units', models.PositiveIntegerField()),
                ('observations', models.TextField()),
                ('next', models.PositiveIntegerField(choices=[(0, 'Terminado'), (1, 'Extrusión'), (2, 'Impresión'), (3, 'Sellado'), (4, 'Manualidad')], default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealings', related_query_name='sealing', to='Production.machine')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sealing', related_query_name='sealing_query', to='Production.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField()),
                ('observations', models.TextField()),
                ('next', models.PositiveIntegerField(choices=[(0, 'Terminado'), (1, 'Extrusión'), (2, 'Impresión'), (3, 'Sellado'), (4, 'Manualidad')], default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', related_query_name='printing', to='Production.machine')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing', related_query_name='printing_query', to='Production.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Handicraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField()),
                ('next', models.PositiveIntegerField(choices=[(0, 'Terminado'), (1, 'Extrusión'), (2, 'Impresión'), (3, 'Sellado'), (4, 'Manualidad')], default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handicrafts', related_query_name='handicraft', to='Production.machine')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicraft', related_query_name='handicraft_query', to='Production.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='extrusion',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrusion', related_query_name='extrusion_query', to='Production.workorder'),
        ),
    ]
