# Generated by Django 5.1.1 on 2024-10-31 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_alter_podetail_id_alter_podetail_wo_number'),
        ('Production', '0003_extrusion_created_at_extrusion_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='po_detail',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='work_order', serialize=False, to='Business.podetail', to_field='wo_number'),
        ),
    ]
