# Generated by Django 5.1.1 on 2024-10-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_remove_workorder_po_detail_alter_workorder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='id',
            new_name='po_detail',
        ),
    ]
