# Generated by Django 5.1.1 on 2024-11-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_rename_id_workorder_po_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_data', models.JSONField()),
                ('changed_fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', related_query_name='change_log', to='Production.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
