# Generated by Django 5.1.1 on 2024-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0006_wochangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Sin iniciar'), (1, 'En extrusión'), (2, 'En impresión'), (3, 'En sellado'), (4, 'En manualidad'), (5, 'En bodega'), (6, 'Terminado'), (7, 'Cancelado'), (8, 'Sin estado')], default=0),
        ),
    ]
