# Generated by Django 5.1.1 on 2024-11-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_alter_workorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='po_detail',
            new_name='id',
        ),
    ]
