# Generated by Django 5.1.1 on 2024-11-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0008_rename_po_detail_workorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrusion',
            name='width',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrusion',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrusion', to='Production.workorder'),
        ),
        migrations.AlterField(
            model_name='handicraf',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handicraft', to='Production.workorder'),
        ),
        migrations.AlterField(
            model_name='printing',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printing', to='Production.workorder'),
        ),
        migrations.AlterField(
            model_name='sealing',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sealing', to='Production.workorder'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='touch', to='Production.workorder'),
        ),
    ]
